ALTER TABLE clients
  DROP COLUMN name,
  DROP COLUMN phone,
  ADD COLUMN first_name VARCHAR(255),
  ADD COLUMN last_name VARCHAR(255),
  ADD COLUMN mobile VARCHAR(50),
  ADD COLUMN landline VARCHAR(50),
  ADD COLUMN nie_number VARCHAR(100),
  ADD COLUMN street_address VARCHAR(255),
  ADD COLUMN town VARCHAR(100),
  ADD COLUMN province VARCHAR(100),
  ADD COLUMN post_code VARCHAR(20);
