ALTER TABLE pos_sessions
  ADD COLUMN end_50 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_20 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_10 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_5 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_coins DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN pdq_total DECIMAL(10,2) NOT NULL DEFAULT 0;
