ALTER TABLE pos_sessions
  ADD COLUMN start_2 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_1 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_0_50 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_0_20 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_0_10 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_0_05 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_2 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_1 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_0_50 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_0_20 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_0_10 INT NOT NULL DEFAULT 0,
  ADD COLUMN end_0_05 INT NOT NULL DEFAULT 0;
