ALTER TABLE pos_sessions
  ADD COLUMN start_50 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_20 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_10 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_5 INT NOT NULL DEFAULT 0,
  ADD COLUMN start_coins DECIMAL(10,2) NOT NULL DEFAULT 0;
