CREATE TABLE IF NOT EXISTS job_work_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  job_id INT NOT NULL,
  action VARCHAR(10) NOT NULL,
  ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_job_work_logs_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);
